fixed some formatting in man pages

diff --git a/trunk/bin/schoolmesh_application_createtables b/trunk/bin/schoolmesh_application_createtables
--- a/trunk/bin/schoolmesh_application_createtables
+++ b/trunk/bin/schoolmesh_application_createtables
@@ -10,26 +10,39 @@ if [ $CONFIG_READ -ne 1 ]; then echo "Error in reading configuration"; exit 1; f
 #@
 #@ # SYNOPSIS
 #@
-#@ {} *environment*
+#@ {} *environment* [--no-confirmation]
 #@
 #@ # DESCRIPTION
 #@
-#@ Use this script to create empty tables in the database (using the schoolmesh
-#@ symfony-generated script).
+#@ Use this script to create empty tables in the database (using the 
+#@ schoolmesh symfony-generated script).
+#@ If the option --no-confirmation is set, the dialog with the 
+#@ confirmation question is not shown.
 #@
 #@ # WARNINGS
 #@ 
-#@ This will delete all the contents of the database. Be sure to make a backup 
-#@ before using it.
+#@ This will delete all the contents of the database. Be sure to make a
+#@ backup before using it.
 #@
 #@ # EXAMPLES
 #@
-#@	{-} prod 
-#@	{-} dev
+#@ {-} prod 
+#@  {-} dev
 
 ENVIRONMENT=$1
 
 checkOneOf $ENVIRONMENT dev prod test
+
+if [[ "$2" != "--no-confirmation" ]]; then
+  dialog --yesno "This operation will erase the current database. Are you sure you want to proceed?" 0 0
+  if [[ $? -eq 1 ]]; then
+    echo "Script aborted"
+    exit 1
+  fi 
+fi
+
+echo "going on"
+exit
 
 SCRIPT=$(mktemp)
 
