started working on shell script wrappers

diff --git a/trunk/bin/schoolmesh_posixaccount_unlockuser b/trunk/bin/schoolmesh_posixaccount_unlockuser
--- a/trunk/bin/schoolmesh_posixaccount_unlockuser
+++ b/trunk/bin/schoolmesh_posixaccount_unlockuser
@@ -1,23 +1,16 @@
 #!/bin/bash
 
-if [ $# -eq 0 ]
-	then
-		echo "This script is a wrapper. See schoolmesh(1) for details."
-		exit 1
-	fi
+CONFIG_READ=0
+source /var/schoolmesh/config/schoolmesh.rc $@
+if [ $CONFIG_READ -ne 1 ]; then echo "Error in reading configuration"; exit 1; fi
 
 USERNAME=$1
 
-getent passwd $USERNAME > /dev/null
-
-if [ $? -ne 0 ] ; then
-	echo "unlocked=0"
-	exit 1
-fi
+checkUsername $USERNAME
 
 sudo usermod -U $USERNAME && sudo chage -E -1 $USERNAME && echo "unlocked=1" && exit 0
 
 echo "unlocked=0"
-exit 2
+exit 99
 
 
